// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

#ifndef PROTOBUF_test_2eproto__INCLUDED
#define PROTOBUF_test_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_test_2eproto();
void protobuf_AssignDesc_test_2eproto();
void protobuf_ShutdownFile_test_2eproto();

class sayHello;

// ===================================================================

class sayHello : public ::google::protobuf::Message {
 public:
  sayHello();
  virtual ~sayHello();

  sayHello(const sayHello& from);

  inline sayHello& operator=(const sayHello& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const sayHello& default_instance();

  void Swap(sayHello* other);

  // implements Message ----------------------------------------------

  sayHello* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const sayHello& from);
  void MergeFrom(const sayHello& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string sayWhat = 1;
  inline bool has_saywhat() const;
  inline void clear_saywhat();
  static const int kSayWhatFieldNumber = 1;
  inline const ::std::string& saywhat() const;
  inline void set_saywhat(const ::std::string& value);
  inline void set_saywhat(const char* value);
  inline void set_saywhat(const char* value, size_t size);
  inline ::std::string* mutable_saywhat();
  inline ::std::string* release_saywhat();
  inline void set_allocated_saywhat(::std::string* saywhat);

  // optional int32 value = 2;
  inline bool has_value() const;
  inline void clear_value();
  static const int kValueFieldNumber = 2;
  inline ::google::protobuf::int32 value() const;
  inline void set_value(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:sayHello)
 private:
  inline void set_has_saywhat();
  inline void clear_has_saywhat();
  inline void set_has_value();
  inline void clear_has_value();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* saywhat_;
  ::google::protobuf::int32 value_;
  friend void  protobuf_AddDesc_test_2eproto();
  friend void protobuf_AssignDesc_test_2eproto();
  friend void protobuf_ShutdownFile_test_2eproto();

  void InitAsDefaultInstance();
  static sayHello* default_instance_;
};
// ===================================================================


// ===================================================================

// sayHello

// required string sayWhat = 1;
inline bool sayHello::has_saywhat() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void sayHello::set_has_saywhat() {
  _has_bits_[0] |= 0x00000001u;
}
inline void sayHello::clear_has_saywhat() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void sayHello::clear_saywhat() {
  if (saywhat_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    saywhat_->clear();
  }
  clear_has_saywhat();
}
inline const ::std::string& sayHello::saywhat() const {
  // @@protoc_insertion_point(field_get:sayHello.sayWhat)
  return *saywhat_;
}
inline void sayHello::set_saywhat(const ::std::string& value) {
  set_has_saywhat();
  if (saywhat_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    saywhat_ = new ::std::string;
  }
  saywhat_->assign(value);
  // @@protoc_insertion_point(field_set:sayHello.sayWhat)
}
inline void sayHello::set_saywhat(const char* value) {
  set_has_saywhat();
  if (saywhat_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    saywhat_ = new ::std::string;
  }
  saywhat_->assign(value);
  // @@protoc_insertion_point(field_set_char:sayHello.sayWhat)
}
inline void sayHello::set_saywhat(const char* value, size_t size) {
  set_has_saywhat();
  if (saywhat_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    saywhat_ = new ::std::string;
  }
  saywhat_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:sayHello.sayWhat)
}
inline ::std::string* sayHello::mutable_saywhat() {
  set_has_saywhat();
  if (saywhat_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    saywhat_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:sayHello.sayWhat)
  return saywhat_;
}
inline ::std::string* sayHello::release_saywhat() {
  clear_has_saywhat();
  if (saywhat_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = saywhat_;
    saywhat_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void sayHello::set_allocated_saywhat(::std::string* saywhat) {
  if (saywhat_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete saywhat_;
  }
  if (saywhat) {
    set_has_saywhat();
    saywhat_ = saywhat;
  } else {
    clear_has_saywhat();
    saywhat_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:sayHello.sayWhat)
}

// optional int32 value = 2;
inline bool sayHello::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void sayHello::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void sayHello::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void sayHello::clear_value() {
  value_ = 0;
  clear_has_value();
}
inline ::google::protobuf::int32 sayHello::value() const {
  // @@protoc_insertion_point(field_get:sayHello.value)
  return value_;
}
inline void sayHello::set_value(::google::protobuf::int32 value) {
  set_has_value();
  value_ = value;
  // @@protoc_insertion_point(field_set:sayHello.value)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_test_2eproto__INCLUDED
